### ISSUE TITLE
Update qed_dask Dockerfile to not pull daskdev image

### ISSUE THREAD

**Issue by JeffreyMinucci** [quanted/qed_kube#11]
This improvement will ensure that dask scheduler and workers always have the same package versions as the rest of our stack. 

We can copy from [the daskdev official dockerfile](https://hub.docker.com/r/daskdev/dask/dockerfile) but switch out their conda install section for code that installs from our requirements.txt.

We may want to just grab the version numbers from requirements.txt for the 8 packages the scheduler/worker needs instead of installing the entire requirements list.

**Comment by deronsmith** [comment]
Updated dask Dockerfile to use dask image as base, builds off image by loading requirements.txt from requirements_qed. Dask base image specified as 2.10.1
