### ISSUE TITLE
aws ebs volumes

### ISSUE THREAD

**Issue by puruckertom** [quanted/qed_kube#5]
Create ebs volumes with hooks to the github repo: see AWS EBS volumes list at the bottom (Kevin), is there an appropriate level of consolidation from 11 to ??
Additional s3 bucket/ec2 instance/something else to hold miscellaneous files of importance (databases, keys, etc.)?? (everyone)
AWS EBS Volumes for QED Kubernetes 
volume_name		used_by			amazon			azure
qed-nginx-certs	qed-nginx			dropbox? 
qed-static		qed-nginx, qed-django	https://github.com/quanted/static_qed
collected-static	qed-django, qed-flask	shared static files flask&django, no initial files
qed-templates		qed-django			https://github.com/quanted/templates_qed
django-secrets	qed-django			dropbox
sam-bin			qed-flask, qed-celery	s3 bucket
qed-basins		qed-flask, qed-celery	s3 bucket
hms-appdata		hms-dotnetcore		(not yet setup, s3 or dropbox)
qed-django		dask-worker			https://github.com/quanted/qed_django
mongodbpv		mongodb				(not yet setup, used as a persistent volume)
postgrespv		postgres				(not yet setup, used as a persistent volume, startup database loading)

**Comment by deronsmith** [comment]
Volumes are mounted from oms-shell pod
